version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:     
        - github.com/spf13/viper.BindEnv
        - github.com/spf13/viper.BindPFlags
        - github.com/spf13/viper.BindPFlag
    staticcheck:
      checks: ["all", "-ST1000"]