basePath: /
definitions:
  api.Order:
    properties:
      accural:
        example: 500
        type: integer
      number:
        example: "42"
        type: string
      status:
        description: |-
          Статус расчёта начисления:
          * REGISTERED - заказ зарегистрирован, но вознаграждение не рассчитано;
          * INVALID - заказ не принят к расчёту, и вознаграждение не будет начислено;
          * PROCESSING - расчёт начисления в процессе;
          * PROCESSED - расчёт начисления окончен;
        enum:
        - REGISTERED
        - INVALID
        - PROCESSING
        - PROCESSED
        example: PROCESSING
        type: string
      uploaded_at:
        example: "2025-06-23T23:48:45+03:00"
        type: string
    type: object
  api.UserRegisterRequest:
    properties:
      login:
        example: user@example.com
        type: string
      password:
        example: password
        type: string
    required:
    - login
    - password
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Накопительная система лояльности «Гофермарт»
  title: Gophermart API
  version: "1.0"
paths:
  /api/user/orders:
    get:
      parameters:
      - description: токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: успешная обработка запроса
          schema:
            items:
              $ref: '#/definitions/api.Order'
            type: array
        "204":
          description: нет данных для ответа
          schema:
            items:
              $ref: '#/definitions/api.Order'
            type: array
        "401":
          description: пользователь не авторизован
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Получение списка загруженных номеров заказов
      tags:
      - orders
    post:
      consumes:
      - text/plain
      parameters:
      - description: номер заказа
        in: body
        name: orderNumber
        required: true
        schema:
          type: string
      - description: токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: номер заказа уже был загружен этим пользователем
        "202":
          description: новый номер заказа принят в обработку
        "400":
          description: неверный формат запроса
        "401":
          description: пользователь не аутентифицирован
        "409":
          description: номер заказа уже был загружен другим пользователем
        "422":
          description: неверный формат номера заказа
        "500":
          description: внутренняя ошибка сервера
      summary: Загрузка номера заказа
      tags:
      - orders
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: данные пользователя для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: пользователь успешно зарегистрирован и аутентифицирован
          headers:
            Authorization:
              description: токен авторизации
              type: string
        "400":
          description: неверный формат запроса
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "409":
          description: логин уже занят
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Регистрация пользователя
      tags:
      - auth
swagger: "2.0"
