basePath: /api/v1
definitions:
  api.Order:
    properties:
      accural:
        example: 500
        type: integer
      number:
        example: 42
        type: integer
      status:
        description: |-
          Статус расчёта начисления:
          * REGISTERED - заказ зарегистрирован, но вознаграждение не рассчитано;
          * INVALID - заказ не принят к расчёту, и вознаграждение не будет начислено;
          * PROCESSING - расчёт начисления в процессе;
          * PROCESSED - расчёт начисления окончен;
        enum:
        - REGISTERED
        - INVALID
        - PROCESSING
        - PROCESSED
        example: PROCESSING
        type: string
      uploaded_at:
        example: "2025-06-23T23:48:45+03:00"
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/user/orders:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Order'
            type: array
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
