basePath: /
definitions:
  api.Order:
    properties:
      accural:
        example: 500
        type: integer
      number:
        example: 42
        type: integer
      status:
        description: |-
          Статус расчёта начисления:
          * REGISTERED - заказ зарегистрирован, но вознаграждение не рассчитано;
          * INVALID - заказ не принят к расчёту, и вознаграждение не будет начислено;
          * PROCESSING - расчёт начисления в процессе;
          * PROCESSED - расчёт начисления окончен;
        enum:
        - REGISTERED
        - INVALID
        - PROCESSING
        - PROCESSED
        example: PROCESSING
        type: string
      uploaded_at:
        example: "2025-06-23T23:48:45+03:00"
        type: string
    type: object
  api.UserRegisterRequest:
    properties:
      login:
        example: user@example.com
        type: string
      password:
        example: password
        type: string
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Накопительная система лояльности «Гофермарт»
  title: Gophermart API
  version: "1.0"
paths:
  /api/user/orders:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Order'
            type: array
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: данные пользователя для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Регистрация пользователя
      tags:
      - user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
